### ISSUE TITLE
"playing_msg" config option not being respected

### ISSUE THREAD

**Issue by adigitalmonk** [adigitalmonk/discordbot-framework#6]
I've set the "playing_msg" option but it looks like it's no longer working for some reason.  Possibly changes in the Discord API?

**Comment by adigitalmonk** [comment]
I think I might need to swap this to using `PresenceData` instead of `setGame` 

https://discord.js.org/#/docs/main/stable/typedef/PresenceData

**Comment by jkys** [comment]
@adigitalmonk, I am having no issues with the playing_msg. However, when I edit the message then restart the bot, it doesn't change for about 2 minutes, but then the change takes place. Is that what you're referring to?

**Comment by jkys** [comment]
It also seems as if you **are** using `setPresence` but you wrapped it using the custom made `setGame` function giving it the illusion you're using the discord.js `game` value.

```javascript
setGame(game, streamingURL) {
    if (!game) return this.setPresence({ game: null });
    return this.setPresence({
      game: {
        name: game,
        url: streamingURL,
      },
    });
```

File: ClientUser.js
Lines: 249 - 256

**Comment by jkys** [comment]
In the discord.js under `ClientUser.js` there this:
```javascript
  /**
   * Sets the game the client user is playing.
   * @param {?string} game Game being played
   * @param {string} [streamingURL] Twitch stream URL
   * @returns {Promise<ClientUser>}
   */
  setGame(game, streamingURL) {
    if (!game) return this.setPresence({ game: null });
    return this.setPresence({
      game: {
        name: game,
        url: streamingURL,
      },
    });
  }
````

So it basically is just a glorified `setPresence`.

**Comment by adigitalmonk** [comment]
Good to hear that it's working (albeit slowly) for you.  Thanks for checking out that `setGame` / `setPresence` idea.  I'll mess around with it some more.  Maybe my own dummy bot has the bug!

**Comment by adigitalmonk** [comment]
No idea why this wasn't working for me previously, but's working now.
